import { execFile } from 'node:child_process';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import { env } from '../config/env.js';
import { AppError } from '../middleware/errorMiddleware.js';

const run = promisify(execFile);
const cleanText = (text) => text.replace(/\u0000/g, '').replace(/[ \t]+\n/g, '\n').replace(/\n{3,}/g, '\n\n').replace(/[ \t]{2,}/g, ' ').trim();
async function renderPage(pdfPath, pageNumber, outputDirectory) { const prefix = path.join(outputDirectory, `page-${pageNumber}`); try { await run(env.pdftoppmPath, ['-f', String(pageNumber), '-l', String(pageNumber), '-jpeg', '-r', '200', pdfPath, prefix], { timeout: 60_000, maxBuffer: 1024 * 1024 }); } catch (error) { if (error.code === 'ENOENT') throw new AppError('OCR_RENDERER_UNAVAILABLE', `PDF renderer not found at "${env.pdftoppmPath}". Install Poppler or configure PDFTOPPM_PATH.`, 503); throw error; } const filename = (await fs.readdir(outputDirectory)).find((file) => file.startsWith(`page-${pageNumber}-`) && file.endsWith('.jpg')); if (!filename) throw new Error(`Could not render page ${pageNumber} for OCR.`); return fs.readFile(path.join(outputDirectory, filename)); }
export async function extractTextWithOcr({ pdfPath, pageNumber }) { if (!env.geminiKey) throw new AppError('AI_NOT_CONFIGURED', 'Gemini API key is not configured for OCR.', 503); const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'knowledge-ai-ocr-')); try { const image = await renderPage(pdfPath, pageNumber, directory); const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${env.ocrModel}:generateContent?key=${env.geminiKey}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, signal: AbortSignal.timeout(90_000), body: JSON.stringify({ generationConfig: { temperature: 0, maxOutputTokens: 8192 }, contents: [{ role: 'user', parts: [{ text: 'Transcribe all readable text from this PDF page exactly. Preserve headings, lists, tables as plain text, and meaningful line breaks. Return only the transcription; do not summarize or add commentary.' }, { inlineData: { mimeType: 'image/jpeg', data: image.toString('base64') } }] }] }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new AppError('OCR_FAILED', payload.error?.message || `OCR failed for page ${pageNumber}.`, 502); const text = cleanText(payload.candidates?.[0]?.content?.parts?.map((part) => part.text || '').join('') || ''); if (!text) throw new AppError('OCR_FAILED', `OCR returned no readable text for page ${pageNumber}.`, 422); return text; } finally { await fs.rm(directory, { recursive: true, force: true }); } }
