import { ObjectId } from 'mongodb';
import { z } from 'zod';
import { chats, chatFilter } from '../models/Chat.js';
import { messages } from '../models/Message.js';
import { documents } from '../models/Document.js';
import { AppError } from '../middleware/errorMiddleware.js';
import { retrieveRelevantChunks } from '../services/retrievalService.js';
import { answerQuestion } from '../services/llmService.js';
const titleSchema = z.object({ title: z.string().trim().min(1).max(120) });
const messageSchema = z.object({ message: z.string().trim().min(1).max(8000) });
export async function listChats(req, res) { const data = await chats().find({ userId: new ObjectId(req.user._id) }).sort({ updatedAt: -1 }).toArray(); res.json({ success: true, data: { chats: data } }); }
export async function createChat(req, res) { const { title } = titleSchema.parse(req.body); const chat = { userId: new ObjectId(req.user._id), title, createdAt: new Date(), updatedAt: new Date() }; const { insertedId } = await chats().insertOne(chat); res.status(201).json({ success: true, data: { chat: { ...chat, _id: insertedId } } }); }
export async function getChatMessages(req, res) { const chat = await chats().findOne(chatFilter(req.params.id, req.user._id)); if (!chat) throw new AppError('CHAT_NOT_FOUND', 'Chat could not be found.', 404); const data = await messages().find({ chatId: chat._id }).sort({ createdAt: 1 }).toArray(); res.json({ success: true, data: { chat, messages: data } }); }
export async function sendMessage(req, res) { const { message } = messageSchema.parse(req.body); const chat = await chats().findOne(chatFilter(req.params.id, req.user._id)); if (!chat) throw new AppError('CHAT_NOT_FOUND', 'Chat could not be found.', 404); const userMessage = { chatId: chat._id, userId: new ObjectId(req.user._id), role: 'user', content: message, sources: [], createdAt: new Date() }; await messages().insertOne(userMessage); const relevant = await retrieveRelevantChunks({ userId: req.user._id, question: message }); const documentIds = relevant.map((chunk) => chunk.documentId); const sourceDocs = await documents().find({ _id: { $in: documentIds } }).toArray(); const byId = new Map(sourceDocs.map((doc) => [doc._id.toString(), doc])); const sources = relevant.map((chunk) => ({ documentId: chunk.documentId, filename: byId.get(chunk.documentId.toString())?.originalName || 'Unknown document', pageNumber: chunk.pageNumber })); const context = relevant.map((chunk, index) => `[${index + 1}] ${chunk.text}`).join('\n\n'); const answer = await answerQuestion({ question: message, context }); const assistantMessage = { chatId: chat._id, userId: new ObjectId(req.user._id), role: 'assistant', content: answer, sources, createdAt: new Date() }; await messages().insertOne(assistantMessage); await chats().updateOne({ _id: chat._id }, { $set: { updatedAt: new Date() } }); res.status(201).json({ success: true, data: { message: assistantMessage } }); }
export async function deleteChat(req, res) { const chat = await chats().findOne(chatFilter(req.params.id, req.user._id)); if (!chat) throw new AppError('CHAT_NOT_FOUND', 'Chat could not be found.', 404); await messages().deleteMany({ chatId: chat._id }); await chats().deleteOne({ _id: chat._id }); res.status(204).send(); }
