import { ObjectId } from 'mongodb';
import { z } from 'zod';
import { chats, chatFilter } from '../models/Chat.js';
import { messages } from '../models/Message.js';
import { documents } from '../models/Document.js';
import { AppError } from '../middleware/errorMiddleware.js';
import { retrieveRelevantChunks } from '../services/retrievalService.js';
import { answerQuestion, streamAnswer } from '../services/llmService.js';
const titleSchema = z.object({ title: z.string().trim().min(1).max(120) });
const messageSchema = z.object({ message: z.string().trim().min(1).max(8000) });
export async function listChats(req, res) { const data = await chats().find({ userId: new ObjectId(req.user._id) }).sort({ updatedAt: -1 }).toArray(); res.json({ success: true, data: { chats: data } }); }
export async function createChat(req, res) { const { title } = titleSchema.parse(req.body); const chat = { userId: new ObjectId(req.user._id), title, createdAt: new Date(), updatedAt: new Date() }; const { insertedId } = await chats().insertOne(chat); res.status(201).json({ success: true, data: { chat: { ...chat, _id: insertedId } } }); }
export async function renameChat(req, res) { const { title } = titleSchema.parse(req.body); const result = await chats().findOneAndUpdate(chatFilter(req.params.id, req.user._id), { $set: { title, updatedAt: new Date() } }, { returnDocument: 'after' }); if (!result) throw new AppError('CHAT_NOT_FOUND', 'Chat could not be found.', 404); res.json({ success: true, data: { chat: result } }); }
export async function getChatMessages(req, res) { const chat = await chats().findOne(chatFilter(req.params.id, req.user._id)); if (!chat) throw new AppError('CHAT_NOT_FOUND', 'Chat could not be found.', 404); const data = await messages().find({ chatId: chat._id }).sort({ createdAt: 1 }).toArray(); res.json({ success: true, data: { chat, messages: data } }); }
export async function sendMessage(req, res) { const { message } = messageSchema.parse(req.body); const chat = await chats().findOne(chatFilter(req.params.id, req.user._id)); if (!chat) throw new AppError('CHAT_NOT_FOUND', 'Chat could not be found.', 404); const userMessage = { chatId: chat._id, userId: new ObjectId(req.user._id), role: 'user', content: message, sources: [], createdAt: new Date() }; await messages().insertOne(userMessage); const relevant = await retrieveRelevantChunks({ userId: req.user._id, question: message }); const documentIds = relevant.map((chunk) => chunk.documentId); const sourceDocs = await documents().find({ _id: { $in: documentIds } }).toArray(); const byId = new Map(sourceDocs.map((doc) => [doc._id.toString(), doc])); const sources = relevant.map((chunk) => ({ documentId: chunk.documentId, filename: byId.get(chunk.documentId.toString())?.originalName || 'Unknown document', pageNumber: chunk.pageNumber })); const context = relevant.map((chunk, index) => `[${index + 1}] ${chunk.text}`).join('\n\n'); const answer = await answerQuestion({ question: message, context }); const assistantMessage = { chatId: chat._id, userId: new ObjectId(req.user._id), role: 'assistant', content: answer, sources, createdAt: new Date() }; await messages().insertOne(assistantMessage); await chats().updateOne({ _id: chat._id }, { $set: { updatedAt: new Date() } }); res.status(201).json({ success: true, data: { message: assistantMessage } }); }
export async function streamMessage(req, res) { const { message } = messageSchema.parse(req.body); const chat = await chats().findOne(chatFilter(req.params.id, req.user._id)); if (!chat) throw new AppError('CHAT_NOT_FOUND', 'Chat could not be found.', 404); const userMessage = { chatId: chat._id, userId: new ObjectId(req.user._id), role: 'user', content: message, sources: [], createdAt: new Date() }; await messages().insertOne(userMessage); const relevant = await retrieveRelevantChunks({ userId: req.user._id, question: message }); if (!relevant.length) throw new AppError('NO_DOCUMENT_MATCH', 'No searchable content was found. Upload a PDF and wait for its status to become ready.', 409); const sourceDocs = await documents().find({ _id: { $in: relevant.map((chunk) => chunk.documentId) } }).toArray(); const names = new Map(sourceDocs.map((doc) => [doc._id.toString(), doc.originalName])); const sources = relevant.map((chunk) => ({ documentId: chunk.documentId, filename: names.get(chunk.documentId.toString()) || 'Unknown document', pageNumber: chunk.pageNumber })); const context = relevant.map((chunk, index) => `[${index + 1}] ${chunk.text}`).join('\n\n'); const startStream = () => { if (!res.headersSent) res.writeHead(200, { 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache, no-transform', Connection: 'keep-alive', 'X-Accel-Buffering': 'no' }); }; const abortController = new AbortController(); req.on('aborted', () => abortController.abort()); res.on('close', () => { if (!res.writableEnded) abortController.abort(); }); try { const answer = await streamAnswer({ question: message, context, signal: abortController.signal, onToken: (token) => { startStream(); if (!res.writableEnded) res.write(`data: ${JSON.stringify({ token })}\n\n`); } }); if (abortController.signal.aborted) return; startStream(); const assistantMessage = { chatId: chat._id, userId: new ObjectId(req.user._id), role: 'assistant', content: answer, sources, createdAt: new Date() }; const { insertedId } = await messages().insertOne(assistantMessage); await chats().updateOne({ _id: chat._id }, { $set: { updatedAt: new Date() } }); res.write(`event: done\ndata: ${JSON.stringify({ message: { ...assistantMessage, _id: insertedId } })}\n\n`); res.end(); } catch (error) { if (abortController.signal.aborted) return; if (!res.headersSent) throw error; res.write(`event: error\ndata: ${JSON.stringify({ message: 'The response was interrupted. Please try again.' })}\n\n`); res.end(); } }
export async function deleteChat(req, res) { const chat = await chats().findOne(chatFilter(req.params.id, req.user._id)); if (!chat) throw new AppError('CHAT_NOT_FOUND', 'Chat could not be found.', 404); await messages().deleteMany({ chatId: chat._id }); await chats().deleteOne({ _id: chat._id }); res.status(204).send(); }
