import { useState } from 'react';
import ChatInput from '../components/ChatInput';
import ChatMessage from '../components/ChatMessage';
import LoadingSpinner from '../components/LoadingSpinner';
import { useChat } from '../hooks/useChat';

export default function ChatPage() {
  const { messages, chats, documents, chat, isStreaming, sendMessage, error, isReady, openChat, newChat, selectDocuments, deleteChat } = useChat(); const [confirmId, setConfirmId] = useState(null);
  const selectedIds = chat?.documentIds?.map(String) || (chat?.documentId ? [String(chat.documentId)] : []); const ready = documents.filter((document) => document.status === 'ready'); const scopeLabel = selectedIds.length ? `${selectedIds.length} document${selectedIds.length > 1 ? 's' : ''} selected` : 'All ready documents';
  const toggleDocument = (id) => { const next = selectedIds.includes(id) ? selectedIds.filter((selected) => selected !== id) : [...selectedIds, id]; selectDocuments(next); };
  return <div className="chat-layout"><aside className="chat-history"><button className="new-chat" onClick={() => newChat(selectedIds)} disabled={isStreaming}>+ New chat</button><div className="chat-sidebar-scroll"><section><p>CHAT HISTORY</p>{chats.length ? chats.map((item) => <div className="chat-history-item" key={item._id}><button className={item._id === chat?._id ? 'selected' : ''} onClick={() => openChat(item._id)} title={item.title}>{item.title}</button><button className="chat-delete" onClick={() => setConfirmId(item._id)} aria-label={`Delete ${item.title}`}>×</button></div>) : <span className="chat-document-status">No conversations yet</span>}</section><section><p>DOCUMENTS</p><label className="document-option"><input type="checkbox" checked={!selectedIds.length} onChange={() => selectDocuments([])} /> All documents</label>{ready.map((document) => <label className="document-option" key={document._id} title={document.originalName}><input type="checkbox" checked={selectedIds.includes(document._id)} onChange={() => toggleDocument(document._id)} /> <span>{document.originalName}</span></label>)}{documents.filter((document) => document.status !== 'ready').map((document) => <span className="chat-document-status" key={document._id} title={document.processingError || ''}>{document.originalName} · {document.status === 'failed' ? 'Failed' : 'Processing…'}</span>)}</section></div></aside><section className="chat-panel"><header className="chat-header"><div><span className="eyebrow">KNOWLEDGEAI</span><h1>Research Assistant</h1></div><span className="ready-dot">{scopeLabel}</span></header><div className="chat-scroll">{messages.map((message) => <ChatMessage key={message.id} message={message} />)}{isStreaming && <LoadingSpinner label="Finding the best sources…" />}{error && <p className="form-error" role="alert">{error}</p>}</div><ChatInput onSend={sendMessage} disabled={isStreaming || !isReady} /><p className="chat-disclaimer">Answers are grounded in the selected document scope.</p></section>{confirmId && <div className="modal-backdrop"><section className="modal"><h2>Delete this conversation?</h2><p>This action cannot be undone.</p><div className="modal-actions"><button className="button button--secondary" onClick={() => setConfirmId(null)}>Cancel</button><button className="button" onClick={() => { deleteChat(confirmId); setConfirmId(null); }}>Delete</button></div></section></div>}</div>;
}
