import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import Button from '../components/Button';
import FileCard from '../components/FileCard';
import UploadModal from '../components/UploadModal';
import { useAuth } from '../hooks/useAuth';
import { documentService } from '../services/documentService';

export default function DashboardPage() { const { user } = useAuth(); const [documents, setDocuments] = useState([]); const [uploadOpen, setUploadOpen] = useState(false); const [error, setError] = useState(''); const loadDocuments = useCallback(async () => { try { const { data } = await documentService.list(); setDocuments(data.documents); } catch (requestError) { setError(requestError.message); } }, []); useEffect(() => { loadDocuments(); }, [loadDocuments]); const upload = async (file) => { const { data } = await documentService.upload(file); setDocuments((current) => [data.document, ...current]); }; const readyDocuments = documents.filter((document) => document.status === 'ready').length; return <><header className="page-header"><div><span className="eyebrow">DASHBOARD</span><h1>Welcome back, {user?.name?.split(' ')[0]} <span>👋</span></h1><p>Your knowledge base is ready when you are.</p></div><Button onClick={() => setUploadOpen(true)}>+ Upload document</Button></header>{error && <p className="form-error" role="alert">{error}</p>}<section className="stat-grid"><div><span>Documents</span><strong>{documents.length}</strong><small>{readyDocuments} ready to search</small></div><div><span>Processing</span><strong>{documents.length - readyDocuments}</strong><small>Documents being prepared</small></div><div><span>Knowledge status</span><strong>{readyDocuments ? 'Ready' : '—'}</strong><small>{readyDocuments ? 'Ask questions in chat' : 'Upload a PDF to begin'}</small></div></section><section className="dashboard-section"><div className="section-heading"><div><h2>Recent documents</h2><p>Your latest knowledge sources.</p></div><Link to="/documents">View all →</Link></div><div className="file-list">{documents.length ? documents.slice(0, 3).map((document) => <FileCard key={document._id} document={document} />) : <p className="empty-state">Your recent documents will appear here.</p>}</div></section><section className="prompt-card"><div><span className="eyebrow">READY TO EXPLORE?</span><h2>Ask something meaningful.</h2><p>Start a conversation with every ready document in your workspace.</p></div><Link to="/chat"><Button>Open AI chat →</Button></Link></section><UploadModal isOpen={uploadOpen} onClose={() => setUploadOpen(false)} onUpload={upload} /></>; }
