import { useState } from 'react';
import { Link } from 'react-router-dom';
import Button from '../components/Button';
import FileCard from '../components/FileCard';
import UploadModal from '../components/UploadModal';
import { useAuth } from '../hooks/useAuth';

const documents = [{ id: 1, name: 'Machine Learning Foundations.pdf', size: '4.8 MB', updatedAt: '2026-09-05', status: 'ready' }, { id: 2, name: 'Research Paper.pdf', size: '2.1 MB', updatedAt: '2026-09-03', status: 'ready' }, { id: 3, name: 'DBMS Notes.pdf', size: '1.2 MB', updatedAt: '2026-09-01', status: 'processing' }];
export default function DashboardPage() { const { user } = useAuth(); const [uploadOpen, setUploadOpen] = useState(false); return <><header className="page-header"><div><span className="eyebrow">DASHBOARD</span><h1>Welcome back, {user?.name?.split(' ')[0]} <span>👋</span></h1><p>Your knowledge base is ready when you are.</p></div><Button onClick={() => setUploadOpen(true)}>+ Upload document</Button></header><section className="stat-grid"><div><span>Documents</span><strong>24</strong><small>3 added this week</small></div><div><span>Conversations</span><strong>18</strong><small>7 this month</small></div><div><span>Knowledge chunks</span><strong>682</strong><small>Across your library</small></div></section><section className="dashboard-section"><div className="section-heading"><div><h2>Recent documents</h2><p>Your latest knowledge sources.</p></div><Link to="/documents">View all →</Link></div><div className="file-list">{documents.map((document) => <FileCard key={document.id} document={document} />)}</div></section><section className="prompt-card"><div><span className="eyebrow">READY TO EXPLORE?</span><h2>Ask something meaningful.</h2><p>Start a conversation with every ready document in your workspace.</p></div><Link to="/chat"><Button>Open AI chat →</Button></Link></section><UploadModal isOpen={uploadOpen} onClose={() => setUploadOpen(false)} onUpload={() => undefined} /></>; }
