import { Link } from 'react-router-dom';
import Navbar from '../components/Navbar';
import Button from '../components/Button';

const features = [['⌁', 'Grounded answers', 'Answers are built from your documents—not generic guesses.'], ['⌕', 'Page-level citations', 'See exactly which document and page informed every answer.'], ['↗', 'Fast retrieval', 'Turn a growing document library into an answerable knowledge base.']];

export default function LandingPage() {
  return <div className="landing"><Navbar /><main><section className="hero"><div className="hero-copy"><span className="eyebrow">YOUR PERSONAL KNOWLEDGE ASSISTANT</span><h1>Your documents,<br /><em>finally useful.</em></h1><p>Upload your research, notes, and reports. Ask natural questions and get grounded answers with clear sources.</p><div className="hero-actions"><Link to="/signup"><Button>Build your knowledge base <span>→</span></Button></Link><a className="text-link" href="#how-it-works">See how it works <span>↓</span></a></div><div className="trust-line"><span>✦</span> Built for curious minds and serious work</div></div><div className="hero-visual"><div className="glow" /><div className="answer-card"><div className="answer-card-header"><span className="mini-logo">✦</span><span>KnowledgeAI</span><i>●</i></div><div className="question-bubble">What are the main findings?</div><div className="ai-answer"><span>✦</span><div><strong>Here’s what I found</strong><p>The study identifies three factors that significantly improve model performance: data quality, feature selection, and evaluation strategy.</p><div className="citation-pill">📄 research-paper.pdf <b>p. 8</b></div><div className="citation-pill">📄 research-paper.pdf <b>p. 12</b></div></div></div></div></div></section><section className="feature-section" id="features"><p className="eyebrow">DESIGNED FOR CLARITY</p><h2>Answers you can trust.</h2><div className="feature-grid">{features.map(([icon, title, body]) => <article key={title} className="feature-card"><span className="feature-icon">{icon}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section><section id="how-it-works" className="how-it-works"><p className="eyebrow">SIMPLE BY DESIGN</p><h2>From upload to insight.</h2><div className="steps"><div><b>01</b><h3>Add your documents</h3><p>Upload PDFs to your private knowledge base.</p></div><div><b>02</b><h3>Ask in plain language</h3><p>Ask the questions that matter to your work.</p></div><div><b>03</b><h3>Trace every answer</h3><p>Review cited sources at the page level.</p></div></div></section></main><footer>© {new Date().getFullYear()} KnowledgeAI <span>Built for better thinking.</span></footer></div>;
}
